INSERT OR IGNORE INTO tips (id, tip) VALUES (0, 'Use `gg` to go to top of file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (1, 'Use `:w` to save your file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (2, 'Use `:q` to quit Vim.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (3, 'Press `u` to undo your last change.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (4, 'Press `Ctrl+r` to redo an undone change.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (5, 'Use `yy` to copy a line.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (6, 'Use `dd` to delete a line.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (7, 'Use `p` to paste after the cursor.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (8, 'Use `P` to paste before the cursor.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (9, 'Press `v` to enter visual mode and select text.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (10, 'Press `Ctrl+v` to select a block of text (visual block mode).');
INSERT OR IGNORE INTO tips (id, tip) VALUES (11, 'Use `:set number` to display line numbers.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (12, 'Use `:set relativenumber` to show relative line numbers.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (13, 'Use `/text` to search for ''text'' within the file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (14, 'Press `n` to go to the next search result.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (15, 'Press `N` to go to the previous search result.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (16, 'Use `:noh` to remove the search highlight.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (17, 'Use `:split` to split the window horizontally.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (18, 'Use `:vsplit` to split the window vertically.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (19, 'Use `Ctrl+w h/j/k/l` to move between split windows.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (20, 'Use `:e filename` to open a file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (21, 'Use `:wq` to save and quit Vim.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (22, 'Use `:q!` to quit without saving.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (23, 'Use `:x` to save and exit, similar to `:wq`.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (24, 'Use `:tabs` to list all open tabs.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (25, 'Use `gt` to switch to the next tab.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (26, 'Use `gT` to switch to the previous tab.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (27, 'Press `Ctrl+d` to scroll down by half a page.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (28, 'Press `Ctrl+u` to scroll up by half a page.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (29, 'Use `:help` to open the help system.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (30, 'Use `:w filename` to save a file with a new name.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (31, 'Use `:set tabstop=4` to set the tab width to 4 spaces.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (32, 'Use `:set shiftwidth=4` to set the indentation width.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (33, 'Use `:set expandtab` to insert spaces instead of tabs.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (34, 'Press `Ctrl+f` to move forward one page in the file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (35, 'Press `Ctrl+b` to move backward one page in the file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (36, 'Use `:read filename` to insert the contents of another file.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (37, 'Use `:!command` to run an external shell command.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (38, 'Use `:%s/old/new/g` to replace all instances of ''old'' with ''new''.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (39, 'Use `:set list` to display hidden characters like tabs and newlines.');
INSERT OR IGNORE INTO tips (id, tip) VALUES (40, 'Use `:set noswapfile` to disable swap file creation.');
